name: vrav_pass
description: Sovereign offline-first password, notes and bookmarks manager with post-quantum ready crypto.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Crypto
  cryptography: ^2.7.0
  pointycastle: ^3.9.1
  convert: ^3.1.1
  crypto: ^3.0.5
  ffi: ^2.1.3

  # Storage
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.2

  # Network / sync
  http: ^1.2.2
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # Files
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # UI & utils
  uuid: ^4.5.1
  intl: any
  easy_localization: ^3.0.7
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/i18n/
    - assets/icons/
